spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/spring-ionic
        username: postgres
        password: root

    jpa:
      properties:
        hibernate:
          jdbc:
            lob:
              "[non_contextual_creation]": true
      hibernate:        ddl-auto: none        
#        javax:
#          persistence:
#            schema-generation:
#              create-source: metadata
#              scripts:
#                action: create
#                create-target: create.sq