spring:
    profiles:
        active: ${APP_PROFILE:test}

    jpa:
        open-in-view: false
        show-sql: true
        properties:
            hibernate:
                "[format_sql]": true

server:
    error:
      include-stacktrace: never 