spring:
    profiles:
        active: ${APP_PROFILE:test}

    jpa:
        show-sql: true
        properties:
            hibernate:
                "[format_sql]": true

server:
    error:
      include-stacktrace: never 
      
jwt:
  secret: sequenciaCaracteresToken
  expiration: 60000  